ZSH_THEME="robbyrussell"

plugins=(
   git
   extract
   cp
   docker
   gradle
 ) 

export PATH=~/.npm-global/bin:$PATH

export PATH="$HOME/.rbenv/bin:$PATH"

source $ZSH/oh-my-zsh.sh

# Use vim-like navigation (press esc to go to 'normal' mode and i go to back to 'insert' mode.
bindkey -v
